### ISSUE TITLE
Rust implementation has not O(n) time complexity

### ISSUE THREAD

**Issue by subtle-byte** [rabbit72/remove-spaces#1]
It is so at least because `target.chars().nth(from_index)` itself has O(n) time complexity and it is placed inside the loop.

Just try to run the `remove_extra_spaces` with a string like `" abc ".repeat(100000)` - it will work endlessly.

Probably a better implementation:
```rust
pub fn remove_extra_spaces(target: &mut String) {
    let mut prev_is_whitespace = true;
    target.retain(|c| {
        let retain = !c.is_whitespace() || !prev_is_whitespace;
        prev_is_whitespace = c.is_whitespace();
        retain
    });
    target.truncate(target.trim_end().len());
}
```

**Comment by rabbit72** [comment]
@subtle-byte yep, you're completely right. Your example is correct and much easier to read. Thanks.

Impressive efficiency of rust's abstractions.
Let's process `" abc ".repeat(100_000_000)`
One unicode symbol of ASCII range (`" abc "`) take 1 byte: `5 x 100_000_000 = 500_000_000 / 2^20 = 476.84 Mb`
It takes `~477` Mb of real memory space.
